const express = require('express');
const router = express.Router();
const getRoutes = require('./get');
const postRoutes = require('./post');
const patchRoutes = require('./patch');
const deleteRoutes = require('./delete');
router.use('/', getRoutes);
router.use('/', postRoutes);
router.use('/', patchRoutes);
router.use('/', deleteRoutes);
router.use('/', deleteRoutes);
module.exports = router;